## Gold Mining Production Data EDA

In [47]:
import pandas as pd
import numpy as np

In [48]:
# Load the Excel file
file_path = 'Gold-Mining-Production-Volumes-Data.xlsx'  # Replace with your actual file path

# Load the Excel file, using the first row as header and skipping the initial title rows
df = pd.read_excel(file_path, sheet_name='Mine Production', skiprows=2)

df.head()

,Country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,Region
0,Canada,102.147231,101.975000,106.373000,131.404000,151.211731,157.667672,163.135951,171.246768,191.881860,185.216037,173.275685,192.902585,194.505410,North America
1,United States,231.252390,233.924832,234.622670,230.120000,210.000000,216.745000,229.100000,236.269370,222.598889,200.400000,193.400000,186.800000,172.700000,North America
2,Mexico,78.655632,94.369868,107.529533,109.771670,113.352992,131.706363,130.739121,119.629900,118.358900,108.984700,110.361100,124.776300,124.035900,North America
3,Peru,184.823620,183.834850,189.763763,182.418724,171.097000,170.531264,166.005603,166.598365,162.550761,143.339033,101.553944,127.339265,125.733064,Central & South America
4,Brazil,71.547000,77.709000,80.173000,89.323000,90.438000,95.400000,98.924000,95.377000,97.000000,100.000000,98.922000,93.084183,86.674596,Central & South America

In [ ]:
df.loc[df['Country'] == 'DR Congo', 'Country'] = 'Democratic Republic of the Congo'
df.loc[df['Country'] == "CÃ´te d'Ivoire", 'Country'] = 'Ivory Coast'

In [49]:
# Save the dataframe as a CSV file
output_csv_path = 'Gold-Mining-Production-Volumes-Data.csv'

df.to_csv(output_csv_path, index=False)

In [50]:
# - load idCountry.csv
df_countryid = pd.read_csv('idCountry.csv')
df_countryid.head()

    id                  name
0  AFG           Afghanistan
1  AGO                Angola
2  ALB               Albania
3  ARE  United Arab Emirates
4  ARG             Argentina

In [51]:
# Fill NaN values in CountryID based on partial string matching
df_merged = df.copy()
df_merged['CountryID'] = np.nan
for idx, row in df_merged[df_merged['CountryID'].isna()].iterrows():
    country_name = row['Country']
    match = df_countryid[df_countryid['name'].str.contains(country_name, case=False, na=False)]
    if not match.empty:
        df_merged.at[idx, 'CountryID'] = match['id'].values[0]
df_merged.head()

,Country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,Region,CountryID
0,Canada,102.147231,101.975000,106.373000,131.404000,151.211731,157.667672,163.135951,171.246768,191.881860,185.216037,173.275685,192.902585,194.505410,North America,CAN
1,United States,231.252390,233.924832,234.622670,230.120000,210.000000,216.745000,229.100000,236.269370,222.598889,200.400000,193.400000,186.800000,172.700000,North America,USA
2,Mexico,78.655632,94.369868,107.529533,109.771670,113.352992,131.706363,130.739121,119.629900,118.358900,108.984700,110.361100,124.776300,124.035900,North America,MEX
3,Peru,184.823620,183.834850,189.763763,182.418724,171.097000,170.531264,166.005603,166.598365,162.550761,143.339033,101.553944,127.339265,125.733064,Central & South America,PER
4,Brazil,71.547000,77.709000,80.173000,89.323000,90.438000,95.400000,98.924000,95.377000,97.000000,100.000000,98.922000,93.084183,86.674596,Central & South America,BRA
5,Colombia,43.605000,45.907000,56.222178,45.968665,47.895506,49.637984,53.157324,53.158184,43.905367,45.476476,53.635195,59.851223,60.439654,Central & South America,COL
6,Bolivia,6.394583,6.513066,10.273000,13.320000,34.687000,22.089000,21.788000,28.593000,31.312000,42.000000,23.207000,45.662000,53.374000,Central & South America,BOL
7,Argentina,63.894324,59.041451,54.236612,49.714669,60.048737,63.871665,57.978863,61.385564,58.338295,52.491090,35.944973,37.038153,41.391987,Central & South America,ARG
8,Chile,39.494000,45.136000,49.936000,51.309000,46.031000,42.501000,46.333000,37.911000,37.066000,38.455000,33.895000,34.248000,33.947823,Central & South America,CHL
9,Venezuela,24.900000,25.500000,21.000000,22.800000,22.700000,22.600000,23.000000,23.000000,26.000000,27.800000,33.360000,35.000000,30.000000,Central & South America,VEN
10,Suriname,20.432825,20.128011,20.003790,18.510786,18.387544,17.393405,21.189264,34.097393,34.252911,32.759913,29.796896,28.267484,28.909180,Central & South America,SUR
11,Ecuador,15.191286,15.629845,15.997656,15.858425,15.297804,14.203125,12.203125,11.500000,11.500000,11.378889,13.539483,21.328275,22.815488,Central & South America,ECU
12,Dominican Republic,0.050000,0.540284,4.179111,26.564407,36.248723,31.154442,37.999466,35.282871,31.695712,31.808671,28.292579,25.496735,22.383370,Central & South America,DOM
13,Guyana,11.928000,13.943000,15.594000,18.413000,17.300000,18.224000,23.003000,22.329000,19.166678,19.747753,18.173481,16.137978,16.225007,Central & South America,GUY
14,Other,22.338823,26.523685,22.070877,22.907755,21.639613,20.203624,18.026140,14.166685,12.457260,14.549613,15.724224,20.598266,19.619750,Central & South America,NaN
15,Bulgaria,2.537651,3.420025,4.252101,4.495988,5.528888,5.398811,5.652837,6.648755,6.754850,7.505861,9.777911,10.141074,8.994725,Europe,BGR
16,Finland,5.758047,6.573895,9.051805,8.535838,7.564882,8.201266,8.574106,8.830782,8.313895,7.695785,8.668911,9.122645,8.532719,Europe,FIN
17,Sweden,6.179170,5.922517,6.105584,6.420904,6.480195,6.346580,6.535629,7.845843,7.865442,8.093242,8.250162,7.324453,7.209770,Europe,SWE
18,Other,2.191700,2.108063,3.474577,4.436304,4.095971,5.280144,7.072483,7.144197,6.560113,6.952000,7.080146,7.912320,10.783747,Europe,NaN
19,Ghana,94.293629,96.781885,105.952885,105.817679,106.324939,95.404581,131.400000,133.344400,149.056788,142.370954,130.113779,124.675578,127.000000,Africa,GHA
20,Mali,42.728904,42.648302,47.611994,55.865334,60.400212,71.422583,82.087825,73.944578,88.303925,96.761823,92.380502,99.287806,101.719382,Africa,MLI
21,Burkina Faso,44.910292,59.720352,56.900428,61.620300,62.187495,54.576094,57.015516,74.579135,77.995732,82.642245,93.373871,102.724630,96.172649,Africa,BFA
22,South Africa,209.964915,205.339620,179.778156,179.542556,168.634308,157.004000,155.014500,147.290000,126.144000,113.185000,102.463000,113.560000,92.560000,Africa,ZAF
23,Sudan,29.328566,32.631052,33.866209,57.555174,60.882898,67.753039,77.474283,88.034283,76.687283,77.998282,81.779282,85.056482,80.056484,Africa,SDN
24,Guinea,25.830151,25.685530,24.320806,25.433358,32.053476,40.993563,45.572857,46.771327,50.836259,57.637991,56.850659,65.035259,63.515676,Africa,GIN
25,Tanzania,47.452843,54.399117,56.314385,51.993600,51.790117,53.202639,55.250648,54.624255,46.333184,46.466618,48.377846,50.389990,50.892027,Africa,TZA
26,Zimbabwe,17.119000,18.994000,22.742000,23.000000,23.181045,25.450000,26.483004,34.495000,51.940100,44.428700,40.873180,46.391330,49.354620,Africa,ZWE
27,CÃ´te d'Ivoire,7.763754,13.201687,13.010705,14.462613,19.380871,22.245222,23.596598,25.660795,24.060000,32.478000,38.000000,41.850000,48.000000,Africa,NaN
28,DR Congo,18.000000,21.000000,24.783341,25.312225,35.874593,42.694644,45.374208,49.601170,62.920992,60.425327,52.366681,49.052078,44.509353,Africa,NaN
29,Niger,6.595608,7.365300,9.564200,9.077460,8.667770,10.874090,8.721720,12.684277,10.684277,14.466553,24.466552,34.466552,34.466552,Africa,NER
30,Liberia,10.000000,10.000000,11.000000,10.000000,10.000000,10.534109,14.403249,13.685700,19.743381,18.584851,18.777745,20.502318,21.283046,Africa,LBR
31,Senegal,5.379302,4.838831,7.415786,8.203287,8.587841,8.669635,10.246624,11.561231,16.460760,17.338531,15.900676,20.177637,19.671125,Africa,SEN
32,Mauritania,8.980928,8.781421,8.246141,9.918037,10.022949,9.112239,8.126708,10.096429,10.735960,15.054149,15.550737,8.103636,19.316688,Africa,MRT
33,Madagascar,10.000000,10.400000,10.800000,11.100000,11.100000,11.700000,13.500000,13.300000,14.000000,14.500000,13.775000,15.515000,15.515000,Africa,MDG
34,Other,43.430656,60.122426,66.553434,69.589428,73.182991,87.878484,104.727698,109.052935,110.737553,109.856410,106.786827,115.362481,115.200138,Africa,NaN
35,Russia,203.071700,211.596000,233.400000,248.497000,252.700000,255.294000,262.361000,280.680000,295.404000,327.155000,331.737000,330.884000,324.673259,Commonwealth of Independent States,RUS
36,Uzbekistan,68.994647,68.125636,77.010400,78.010425,79.454622,78.999982,89.999990,91.111840,91.581503,93.155042,100.156012,104.859671,110.840916,Commonwealth of Independent States,UZB
37,Kazakhstan,29.910565,35.570223,37.270350,44.090370,42.592971,51.999624,58.721267,67.214154,73.894108,74.624936,79.200150,76.606078,81.861056,Commonwealth of Independent States,KAZ
38,Kyrgyzstan,18.960344,19.687899,11.347548,20.218058,19.349244,18.687829,21.249867,21.046002,21.926365,26.000000,24.285991,25.676103,29.344042,Commonwealth of Independent States,KGZ
39,Other,9.596381,9.024936,8.200765,8.677667,9.117043,11.892691,12.596841,18.649159,18.123855,20.623423,20.279896,18.510491,18.407836,Commonwealth of Independent States,NaN
40,China,351.126242,371.206747,413.296661,438.413053,462.049155,460.302963,463.736476,429.140000,404.120000,383.200000,368.340000,331.982938,375.048000,Asia,CHN
41,Indonesia,132.263835,110.221302,82.611642,89.990581,93.465989,115.100616,118.428078,117.609149,153.000000,92.304759,100.900000,116.446652,124.927482,Asia,IDN
42,Philippines,40.847000,38.120000,30.762000,29.248000,28.423000,30.643000,36.674000,44.749000,42.765000,34.646000,25.564000,27.992000,38.607000,Asia,PHL
43,Turkey,16.431124,23.966709,29.370100,33.499194,31.239670,28.230070,24.426620,24.693220,22.876860,37.114630,41.504760,39.365277,30.935094,Asia,TUR
44,Mongolia,13.956863,13.342101,14.234446,19.692481,31.983802,32.818241,21.327933,22.493900,22.581900,16.251000,20.225300,19.220850,19.382730,Asia,MNG
45,Laos,5.488481,4.333329,6.763596,7.187816,5.598867,7.243039,7.114446,6.357543,5.928626,5.557251,5.849717,11.634394,13.372876,Asia,LAO
46,Other,44.625286,45.130281,46.137721,45.893469,47.062553,48.094524,47.460010,46.093000,48.506023,51.134809,47.912327,47.486669,49.736222,Asia,NaN
47,Australia,256.713296,258.698719,250.440736,267.061610,274.047217,279.189568,287.690277,292.531794,313.028306,325.148363,327.951560,307.170182,313.872485,Oceania,AUS
48,Papua New Guinea,69.668937,63.846259,58.969858,64.582537,58.386372,60.901668,62.883507,63.009467,67.073240,71.152025,52.465278,40.899261,41.594766,Oceania,PNG
49,New Zealand,12.065440,11.223623,9.677260,11.839500,10.758125,11.674216,9.603098,9.038881,9.262546,7.830510,5.460363,5.262763,6.038919,Oceania,NZL
50,Other,1.979321,3.433175,3.579455,3.138314,1.994142,1.567993,1.550015,1.550015,1.550015,1.550015,1.550015,1.564015,1.564015,Oceania,NaN

In [53]:
all_nan = df_merged[df_merged['CountryID'].isna()]
all_nan

,Country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,Region,CountryID
14,Other,22.338823,26.523685,22.070877,22.907755,21.639613,20.203624,18.026140,14.166685,12.457260,14.549613,15.724224,20.598266,19.619750,Central & South America,NaN
18,Other,2.191700,2.108063,3.474577,4.436304,4.095971,5.280144,7.072483,7.144197,6.560113,6.952000,7.080146,7.912320,10.783747,Europe,NaN
27,CÃ´te d'Ivoire,7.763754,13.201687,13.010705,14.462613,19.380871,22.245222,23.596598,25.660795,24.060000,32.478000,38.000000,41.850000,48.000000,Africa,NaN
28,DR Congo,18.000000,21.000000,24.783341,25.312225,35.874593,42.694644,45.374208,49.601170,62.920992,60.425327,52.366681,49.052078,44.509353,Africa,NaN
34,Other,43.430656,60.122426,66.553434,69.589428,73.182991,87.878484,104.727698,109.052935,110.737553,109.856410,106.786827,115.362481,115.200138,Africa,NaN
39,Other,9.596381,9.024936,8.200765,8.677667,9.117043,11.892691,12.596841,18.649159,18.123855,20.623423,20.279896,18.510491,18.407836,Commonwealth of Independent States,NaN
46,Other,44.625286,45.130281,46.137721,45.893469,47.062553,48.094524,47.460010,46.093000,48.506023,51.134809,47.912327,47.486669,49.736222,Asia,NaN
50,Other,1.979321,3.433175,3.579455,3.138314,1.994142,1.567993,1.550015,1.550015,1.550015,1.550015,1.550015,1.564015,1.564015,Oceania,NaN